#!/bin/sh
# nb - Nota Bene, a quick note-taking tool for Emacs
#
# nb <search terms>

cd ~/NB

FILES=$(ls -1t | grep -v '~$')

for rx in "$@"; do
  FILES=$(echo "$FILES" | xargs grep -la -i -e "$rx")
done

for f in $FILES; do
  export HEAD=$(tail -n+2 ./"$f" | head -c80 | tr -s '\n\t' ' ')
  stat -c "%n %y" -- "$f" | awk '{printf("%-69s %s\n",
          substr($1 "  " ENVIRON["HEAD"], 0, 69), $2) }'
done

[ -n "$FILES" ] || exit 1
