#!/bin/sh
# nb - Nota Bene, a quick note-taking tool for Emacs
#
# nb <search terms>

cd ~/NB

FILES=$(find . -type f -a ! -name "*~" -print)

for rx in "$@"; do
  FILES=$(echo "$FILES" | xargs grep -la "$rx")
done

for f in $FILES; do
  export HEAD=$(tail -n+2 $f | head -c80 | tr -s '\n\t' ' ')
  stat -c "%n %y" $f | awk '{printf("%-69s %s\n",
          substr($1 "  " ENVIRON["HEAD"], 3, 69), $2) }'
done

[ -n "$FILES" ] || exit 1
